[package]
name = "trust-graph"
version = "0.2.1"
authors = ["Fluence Labs"]
edition = "2018"
description = "trust graph"
license = "Apache-2.0"
repository = "https://github.com/fluencelabs/trust-graph"

[dependencies]
libp2p-core = { package = "fluence-fork-libp2p-core", version = "0.27.1" }
serde = { version = "=1.0.118", features = ["derive"] }

fluence-identity = { version = "0.2.1", path = "identity" }
serde_json = "1.0.58"
bs58 = "0.3.1"
failure = "0.1.6"
log = "0.4.11"
ref-cast = "1.0.2"
derivative = "2.1.1"
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
rand = "0.7.0"
signature = "1.3.0"
serde_with = "1.6.0"
thiserror = "1.0.23"
