[workspace]
members = [
    "keypair",
    "service"
]

[workspace.dependencies]
libp2p-identity = { version = "0.1.0", default-features = false, features = ["peerid", "rsa", "ed25519", "secp256k1", "multihash"] }
