version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  Build:
    docker:
      - image: circleci/rust:latest
    resource_class: xlarge
    environment:
      RUST_BACKTRACE: 1
    steps:
      - checkout
      - run: |
          sudo bash .github/download_marine.sh
      - restore_cache:
          keys:
            - trust-graph00-{{ checksum "./service/Cargo.lock" }}-{{ checksum "./Cargo.lock" }}-{{ checksum "./keypair/Cargo.lock" }}
      - run: |
          rustup target add wasm32-wasi
          cargo test --no-fail-fast --release --all-features --
          cd ./service
          ./build.sh
          mkdir data
          cargo test --no-fail-fast --release --all-features -- --test-threads=1
      - save_cache:
          paths:
            - ~/.cargo
            - ~/.rustup
          key: trust-graph00-{{ checksum "./Cargo.lock" }-{{ checksum "./service/Cargo.lock" }}}-{{ checksum "./keypair/Cargo.lock" }}


workflows:
  version: 2
  CircleCI:
    jobs:
      - Build
