version: 2.1

orbs:
  docker: circleci/docker@1.5.0

jobs:
  Build:
    docker:
      - image: circleci/rust:latest
    resource_class: xlarge
    environment:
      RUST_BACKTRACE: 1
    steps:
      - checkout
      - run: |
          sudo bash .github/download_marine.sh
      - restore_cache:
          keys:
            - trust-graph00-{{ checksum "./service/Cargo.lock" }}-{{ checksum "./Cargo.lock" }}-{{ checksum "./keypair/Cargo.lock" }}
      - run: |
          rustup toolchain install nightly-2021-04-24-x86_64-unknown-linux-gnu
          rustup default nightly-2021-04-24-x86_64-unknown-linux-gnu
          cargo test --no-fail-fast --release --all-features --
      - save_cache:
          paths:
            - ~/.cargo
            - ~/.rustup
          key: trust-graph00-{{ checksum "./Cargo.lock" }}-{{ checksum "./keypair/Cargo.lock" }}


workflows:
  version: 2
  CircleCI:
    jobs:
      - Build
