modules_dir = "artifacts/"

[[module]]
    name = "sqlite3"
    logger_enabled = true

[[module]]
    name = "trust-graph"
    logger_enabled = true

    [module.wasi]
    preopened_files = ["/tmp"]
    mapped_dirs = { "tmp" = "/tmp" }
