name: Run tests with workflow_call

on:
  workflow_call:

jobs:
  trust-graph:
    name: "cargo nextest"
    runs-on: builder

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Setup marine
        uses: fluencelabs/setup-marine@v1
        with:
          artifact-name: marine

      - name: Build
        run: ./build.sh

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -Z unstable-options --all

      - name: Setup nextest
        uses: taiki-e/install-action@nextest

      - name: Run cargo nextest
        env:
          NEXTEST_RETRIES: 10
          NEXTEST_TEST_THREADS: 10
        # exclude distro since at this point we don't have compiled wasms which are required for compilation
        run: cargo nextest run --release --all-features --no-fail-fast --workspace --exclude trust-graph-distro

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://registry.npmjs.org"
          cache-dependency-path: "aqua/package-lock.json"
          cache: "npm"

      - run: npm i
        working-directory: aqua

      - run: npm run build
        working-directory: aqua
