modules_dir = "."
total_memory_limit = "Infinity"

[[module]]
    name = "sqlite3"
    logger_enabled = true

    [module.wasi]
        mapped_dirs = { "tmp" = "data" }
[[module]]
    name = "trust-graph"
    logger_enabled = true

    [module.wasi]
        mapped_dirs = { "tmp" = "data" }
